### PR TITLE
feat: support prop `defaultInView`

### PR DESCRIPTION
**Pull request by hoangnguyen1247**
support prop `defaultInView`

### CODE REVIEW

**Comment by hoangnguyen1247** [comment]
Hi @bitmap, please consider to support prop `defaultInView`

**Comment by hoangnguyen1247** [comment]
Additional information, in my case `ref` component is in viewport default, but i see `isVisible` value always return false for the first time.

**Comment by bitmap** [comment]
Thanks for the PR. Looks good, I'll get this published today.

**Comment by bitmap** [comment]
Version [4.4.0](https://www.npmjs.com/package/react-hook-inview/v/4.4.0) is published with the `defaultInView` option. Thanks for using my hook :)

**Comment by hoangnguyen1247** [comment]
Thank you

**Pull request merged**
